name: UC Irvine Solar Car
markdown: kramdown
permalink: /Blog/:year/:month/:day/:title
baseurl: "www.ucirvinesolarcar.com"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

excerpt_separator: <!--more-->
