name: UC Irvine Solar Car
markdown: kramdown
permalink: /Blog/:year/:month/:day/:title
url: www.ucirvinesolarcar.com/Blog/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
